module.exports = () => {
  const env = {
    NEXT_PUBLIC_PAT: process.env.PAT,
    NEXT_PUBLIC_DEPLOY_ENV: process.env.DEPLOY_ENV,
    NEXT_PUBLIC_PINATA_JWT: process.env.PINATA_JWT
  };

  const config = {
    reactStrictMode: true,
    env,
    images: {
      domains: [
        'githubusercontent.com',
        'assets.coingecko.com',
        'avatars.githubusercontent.com',
        'raw.githubusercontent.com',
        'cryptologos.cc',
        'wallet-asset.matic.network',
        'polygonscan.com',
        'etherscan.io',
        'gateway.pinata.cloud',
        'svgshare.com',
        'coinpoker.com',
        'i.imgur.com',
        'github.com',
        'btu-protocol.com',
        'img.ex-sports.io',
        'pruf.io',
        'arch-finance-basket-logos.s3.amazonaws.com',
        'images.ctfassets.net',
        'www.uct-token.org',
        'www.dropbox.com',
        's2.coinmarketcap.com',
        'www.fleato.com',
        'cdn.efinity.io',
        'cryptopia.com',
        'cryptopia.com',
        'app.insurace.io',
        'd26jz7p3kula4l.cloudfront.net',
        'i.ibb.co',
        'crazydefenseheroes.com',
        'insuretoken.net',
        'arweave.net',
        'drive.google.com',
        'www.germoney.cash',
        'www.lepasa.com',
        'app.civfund.org',
        'minatodao.com',
        'bafkreiawezzhlphckhopkolrkxsz4mtayjz4cjxz4bgsvvkjsclqacf2be.ipfs.nftstorage.link',
        'www.theranosco.in',
        'uploads-ssl.webflow.com',
        'changenow.io',
        'navcoin.org',
        'miguelpiedrafita.com',
        'deversifi.com',
        'user-images.githubusercontent.com',
        'lens.infura-ipfs.io', 
        'ipfs.infura.io', 
        'ipfs.io',
        'cf-ipfs.com',
      ],
    },
  };

  return config;
};
