import Head from "next/head";
import Image from "next/image";
import UploadFile from "../../components/UploadFile/UploadFile";
import { useRouter } from 'next/router';

export default function Upload() {
	const router = useRouter();
	const { pullRequestId } = router.query;

	return (
		<div>
			<Head>
				<title>EthBerlin 2022</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<h1>VidQ</h1>
				<div></div>
				<UploadFile pullRequestId={pullRequestId} />
			</main>
		</div>
	);
}
