import Head from "next/head";
import Image from "next/image";
import FileUpload from "../../components/UploadFile/UploadFile";

export default function Upload() {
	return (
		<div className={styles.container}>
			<Head>
				<title>EthBerlin 2022</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>

				<h1 className={styles.title}>VidQ</h1>

				<div className={styles.grid}></div>

				<FileUpload />
			</main>
		</div>
	);
}
