import Head from "next/head";
import Image from "next/image";
import { Web3ReactProvider } from '@web3-react/core';
import '../styles/globals.css';
import ConnectButton from "../components/WalletConnect/ConnectButton";
import StoreProvider from "../store/Store/StoreProvider";

export default function App({ Component }) {
  return (
    <div>
      <Head>
        <title>EthBerlin 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StoreProvider>
        <Web3ReactProvider>
          <Component />
        </Web3ReactProvider>
      </StoreProvider>
    </div>
  );
}
