import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import ConnectButton from "../components/WalletConnect/ConnectButton";
import FileUpload from "../components/UploadFile/UploadFile";

export default function App({ Component }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>EthBerlin 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component />
    </div>
  );
}
