import Head from "next/head";
import { Web3ReactProvider } from "@web3-react/core";
import "../styles/globals.css";
import StoreProvider from "../store/Store/StoreProvider";
import { ethers } from 'ethers';

export default function App({ Component }) {
  function getLibrary(provider) {
    const library = new ethers.providers.Web3Provider(provider);
    library.pollingInterval = 12000;
    return library;
  }
  return (
    <div>
      <Head>
        <title>EthBerlin 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StoreProvider>
        <Web3ReactProvider getLibrary={getLibrary}>
          <Component />
        </Web3ReactProvider>
      </StoreProvider>
    </div>
  );
}
